Solution of day 9
scalacenter/scala-advent-of-code pull request #673
Opened 2024-12-09 20:45 UTC by dyvrl

2024-12-09 22:22 UTC, makingthematrix requested changes

2024-12-09 22:22 UTC, makingthematrix commented on docs/2024/puzzles/day09.md
> +    return disk
No need for `return` here, just make `zippedGroups.flatMap` from above the last expression in the method.

2024-12-09 22:22 UTC, makingthematrix commented on docs/2024/puzzles/day09.md
> +enum Block(val size: Int):
Just a cosmetic issue, but here you use 4 spaces for an indent while everywhere else it's 2.

2024-12-09 22:22 UTC, makingthematrix commented on docs/2024/puzzles/day09.md
> +    return disk
Let's get rid of the `return` here as well.

2024-12-10 15:43 UTC, merged

2024-12-10 15:43 UTC, SethTisue commented
Thank you!

2024-12-11 01:47 UTC, SethTisue commented
fwiw, my day 9 solution is highly similar, but I managed to do without index-based logic for the recursion in part 2, by using `span`. you might enjoy: https://github.com/SethTisue/adventofcode/blob/main/2024/src/test/scala/Day09.scala#L65